name: Publish Scrypted Home Assistant Image

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag"
        required: true
      package_version:
        description: "Package Version"
        required: false
  workflow_run:
    workflows: ["Publish Scrypted Docker Image"]
    types:
      - completed

jobs:
  home_assistant:
    name: Push Docker image to Docker Hub
    if: ${{ !github.event.action || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: server

      - name: Print Version
        run: echo "Version ${{ github.event.inputs.package_version || steps.package-version.outputs.current-version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Home Assistant image
        uses: docker/build-push-action@v3
        with:
          context: ha_addon/
          file: ha_addon/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            ${{ format('koush/scrypted:homeassistant-v{0}', github.event.inputs.package_version || steps.package-version.outputs.current-version) }}
            ${{ github.event.inputs.docker_tag == 'latest' && 'koush/scrypted:homeassistant' || '' }}

            ${{ format('ghcr.io/koush/scrypted:homeassistant-v{0}', github.event.inputs.package_version || steps.package-version.outputs.current-version) }}
            ${{ github.event.inputs.docker_tag == 'latest' && 'ghcr.io/koush/scrypted:homeassistant' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
